"""Outbound email for Nightjar.

Three primitives, each with a different audit/footer policy:

  - notify_principal(): send to the principal directly. No footer, no
    audit copy (the recipient already IS the principal).
  - send_to_contact(): send to a third party. Footer is appended. A
    parallel audit copy is sent to the principal as a second,
    independent SMTP transaction. On audit failure the audit is queued
    in `pending_audits` for retry.
  - send_audit_retry(): re-attempt one queued audit. Used by the retry
    loop (a future build step).

Two SMTP transactions per send_to_contact, never BCC. The recipient's
"show original" view never reveals the principal's address.

The footer is hardcoded here, not configurable, not generated by the
LLM. It exists so every contact who ever receives Nightjar mail can
inspect what it has noted about them, erase that record, or stop
contact entirely. See DESIGN.md "Contact-initiated control" for why
this is undisableable.

This module is stdlib-only: smtplib + email.message.EmailMessage.
"""
from __future__ import annotations

import logging
import smtplib
import time
from dataclasses import dataclass
from email.message import EmailMessage
from email.utils import formatdate, make_msgid
from typing import Iterable

from .config import SmtpConfig
from .log import JSONLLogger
from .state import State


logger = logging.getLogger(__name__)


# The hardcoded footer appended to every send_to_contact body. Keep this
# in sync with DESIGN.md "Contact-initiated control" and the future
# command parser that recognises these reply phrases.
CONTACT_FOOTER = """\
---
Nightjar is an AI assistant. To see what it has noted about you,
reply "show my notes". To erase those notes, reply "delete my data".
To stop receiving messages from this assistant, reply "stop
contacting me".
"""


class SmtpNotConfiguredError(RuntimeError):
    """Raised when an outbound primitive is called but [smtp] is missing."""


class NotifierError(RuntimeError):
    """Raised when an outbound primitive fails terminally (both sends down)."""


@dataclass(frozen=True)
class SendResult:
    """Outcome of a single primary send.

    `audit_queued` is True when the audit copy failed and was queued
    in pending_audits. `audit_id` is the queued row id in that case.
    """
    primary_message_id: str
    primary_sent: bool
    audit_sent: bool
    audit_queued: bool
    audit_id: int | None
    error: str | None = None


def _build_message(
    *,
    smtp: SmtpConfig,
    to_addr: str,
    subject: str,
    body: str,
    in_reply_to: str | None = None,
    references: Iterable[str] | None = None,
) -> EmailMessage:
    """Construct a stdlib EmailMessage with the canonical Nightjar headers.

    The Message-ID is generated here so the caller can reference the
    same id in audit copies, log lines, and pending_audits rows.
    """
    msg = EmailMessage()
    msg["From"] = f"{smtp.from_name} <{smtp.from_addr}>" if smtp.from_name else smtp.from_addr
    msg["To"] = to_addr
    msg["Subject"] = subject
    msg["Date"] = formatdate(localtime=True)
    msg["Message-ID"] = make_msgid(domain=smtp.from_addr.split("@", 1)[1])
    if in_reply_to:
        msg["In-Reply-To"] = in_reply_to
        msg["References"] = " ".join(references) if references else in_reply_to
    msg.set_content(body)
    return msg


def _smtp_send(smtp: SmtpConfig, msg: EmailMessage) -> None:
    """Single SMTP transaction. Raises on failure.

    Caller is responsible for catching exceptions and deciding what to
    do (retry, queue, panic). The function is intentionally narrow:
    one connection, one send, close.
    """
    with smtplib.SMTP(smtp.host, smtp.port, timeout=30) as conn:
        conn.ehlo()
        conn.starttls()
        conn.ehlo()
        conn.login(smtp.user, smtp.password)
        conn.send_message(msg)


def _format_audit(
    *,
    primary_to: str,
    primary_subject: str,
    primary_message_id: str,
    primary_body: str,
    sent_at_iso: str,
    in_reply_to: str | None,
    approval_token: str | None,
    delivery_failed: bool,
) -> tuple[str, str]:
    """Build the (subject, body) of the audit copy.

    Subject pattern per DESIGN.md: `[Nightjar Audit] To <recipient>,
    <original subject>`.

    Body has a structured header block followed by the literal body
    that was sent (so the principal sees exactly what the contact
    will see, footer and all). When the primary delivery failed, a
    `(SEND FAILED)` banner is prepended and the principal is being
    informed that nothing reached the contact.
    """
    audit_subject = f"[Nightjar Audit] To {primary_to}, {primary_subject}"

    header_lines = [
        f"To: {primary_to}",
        f"Subject: {primary_subject}",
        f"Sent-at: {sent_at_iso}",
        f"Message-ID: {primary_message_id}",
    ]
    if in_reply_to:
        header_lines.append(f"In-Reply-To: {in_reply_to}")
    if approval_token:
        header_lines.append(f"Approval-Token: {approval_token}")
    header_block = "\n".join(header_lines)

    if delivery_failed:
        banner = (
            "(SEND FAILED)\n"
            "Nightjar attempted to send the message below but the SMTP\n"
            "transaction failed. The contact has NOT received this email.\n"
            "The original message has been moved to EXECUTION_FAILED.\n"
            "\n"
        )
    else:
        banner = ""

    audit_body = (
        f"{banner}"
        f"--- audit headers ---\n"
        f"{header_block}\n"
        f"--- begin sent body ---\n"
        f"{primary_body}\n"
        f"--- end sent body ---\n"
    )
    return audit_subject, audit_body


# ---- Public primitives -----------------------------------------------------


def notify_principal(
    *,
    smtp: SmtpConfig | None,
    principal_addr: str,
    subject: str,
    body: str,
    jlogger: JSONLLogger | None = None,
    in_reply_to: str | None = None,
) -> SendResult:
    """Send to the principal. No footer, no audit copy.

    Used for: panic notifications, daily digests, replies to principal
    commands, audit-failure pings. The recipient is the principal so
    sending an audit copy would just be a duplicate.
    """
    if smtp is None:
        raise SmtpNotConfiguredError(
            "[smtp] is required to send mail; add it to nightjar.conf"
        )
    msg = _build_message(
        smtp=smtp,
        to_addr=principal_addr,
        subject=subject,
        body=body,
        in_reply_to=in_reply_to,
    )
    primary_id = msg["Message-ID"]
    try:
        _smtp_send(smtp, msg)
    except Exception as e:
        if jlogger is not None:
            jlogger.event(
                "notify_principal_failed",
                level="error",
                to_addr=principal_addr,
                subject=subject,
                error=type(e).__name__,
                message=str(e),
            )
        return SendResult(
            primary_message_id=primary_id,
            primary_sent=False,
            audit_sent=False,
            audit_queued=False,
            audit_id=None,
            error=f"{type(e).__name__}: {e}",
        )
    if jlogger is not None:
        jlogger.event(
            "notify_principal_sent",
            to_addr=principal_addr,
            subject=subject,
            message_id=primary_id,
        )
    return SendResult(
        primary_message_id=primary_id,
        primary_sent=True,
        audit_sent=False,
        audit_queued=False,
        audit_id=None,
    )


def send_to_contact(
    *,
    smtp: SmtpConfig | None,
    state: State,
    principal_addr: str,
    contact_addr: str,
    subject: str,
    body: str,
    jlogger: JSONLLogger | None = None,
    in_reply_to: str | None = None,
    references: Iterable[str] | None = None,
    approval_token: str | None = None,
) -> SendResult:
    """Send to a third-party contact with mandatory footer + audit copy.

    Two independent SMTP transactions:
      1. Primary send to `contact_addr` with the footer appended.
      2. Audit send to `principal_addr` containing the literal body.

    Failure semantics:
      - Primary fails: audit is still attempted, with a (SEND FAILED)
        banner. Caller (the watcher / future principal-command flow)
        is expected to transition the source message to EXECUTION_FAILED.
      - Audit fails after primary succeeds: audit row is queued in
        pending_audits and the principal is pinged separately. The
        primary delivery is NOT rolled back (you can't unsend email).
      - Both fail: queued audit + error returned.
    """
    if smtp is None:
        raise SmtpNotConfiguredError(
            "[smtp] is required to send mail; add it to nightjar.conf"
        )

    body_with_footer = body.rstrip() + "\n\n" + CONTACT_FOOTER

    primary_msg = _build_message(
        smtp=smtp,
        to_addr=contact_addr,
        subject=subject,
        body=body_with_footer,
        in_reply_to=in_reply_to,
        references=references,
    )
    primary_id = primary_msg["Message-ID"]
    sent_at_iso = primary_msg["Date"]

    primary_sent = False
    primary_error: str | None = None
    try:
        _smtp_send(smtp, primary_msg)
        primary_sent = True
    except Exception as e:
        primary_error = f"{type(e).__name__}: {e}"
        if jlogger is not None:
            jlogger.event(
                "send_to_contact_primary_failed",
                level="error",
                to_addr=contact_addr,
                subject=subject,
                message_id=primary_id,
                error=type(e).__name__,
                message=str(e),
            )

    # Audit copy is attempted regardless of primary outcome. If the
    # primary failed, the audit gets a (SEND FAILED) banner so the
    # principal knows nothing reached the contact.
    audit_subject, audit_body = _format_audit(
        primary_to=contact_addr,
        primary_subject=subject,
        primary_message_id=primary_id,
        primary_body=body_with_footer,
        sent_at_iso=sent_at_iso,
        in_reply_to=in_reply_to,
        approval_token=approval_token,
        delivery_failed=not primary_sent,
    )
    audit_msg = _build_message(
        smtp=smtp,
        to_addr=principal_addr,
        subject=audit_subject,
        body=audit_body,
    )

    audit_sent = False
    audit_queued = False
    audit_id: int | None = None
    audit_error: str | None = None
    try:
        _smtp_send(smtp, audit_msg)
        audit_sent = True
        if jlogger is not None:
            jlogger.event(
                "send_to_contact_audit_sent",
                to_addr=principal_addr,
                subject=audit_subject,
                primary_message_id=primary_id,
            )
    except Exception as e:
        audit_error = f"{type(e).__name__}: {e}"
        audit_id = state.queue_audit(
            primary_message_id=primary_id,
            to_addr=principal_addr,
            subject=audit_subject,
            body=audit_body,
            first_error=audit_error,
        )
        audit_queued = True
        if jlogger is not None:
            jlogger.event(
                "send_to_contact_audit_queued",
                level="warn",
                to_addr=principal_addr,
                subject=audit_subject,
                primary_message_id=primary_id,
                audit_id=audit_id,
                error=type(e).__name__,
                message=str(e),
            )

    if primary_sent and jlogger is not None:
        jlogger.event(
            "send_to_contact_primary_sent",
            to_addr=contact_addr,
            subject=subject,
            message_id=primary_id,
            audit_sent=audit_sent,
            audit_queued=audit_queued,
        )

    return SendResult(
        primary_message_id=primary_id,
        primary_sent=primary_sent,
        audit_sent=audit_sent,
        audit_queued=audit_queued,
        audit_id=audit_id,
        error=primary_error or audit_error,
    )


def send_audit_retry(
    *,
    smtp: SmtpConfig,
    state: State,
    audit_row: dict,
    jlogger: JSONLLogger | None = None,
) -> bool:
    """Re-attempt one queued audit copy. Returns True on success.

    Used by the future audit retry loop. Kept here (not in a separate
    retry module) so all SMTP-touching code lives together and the
    audit subject/body formatting stays in one place.
    """
    audit_msg = _build_message(
        smtp=smtp,
        to_addr=audit_row["to_addr"],
        subject=audit_row["subject"],
        body=audit_row["body"],
    )
    try:
        _smtp_send(smtp, audit_msg)
    except Exception as e:
        state.mark_audit_attempt(
            audit_id=audit_row["id"],
            success=False,
            error=f"{type(e).__name__}: {e}",
            at=int(time.time()),
        )
        if jlogger is not None:
            jlogger.event(
                "audit_retry_failed",
                level="warn",
                audit_id=audit_row["id"],
                attempts=audit_row["attempts"] + 1,
                error=type(e).__name__,
                message=str(e),
            )
        return False
    state.mark_audit_attempt(audit_id=audit_row["id"], success=True)
    if jlogger is not None:
        jlogger.event(
            "audit_retry_sent",
            audit_id=audit_row["id"],
            to_addr=audit_row["to_addr"],
        )
    return True
